version: '2'

services:
  grafana:
    image: grafana/grafana:4.2.0
    ports:
      - "3000:3000"
    environment: 
      GF_SECURITY_ADMIN_PASSWORD: "secret"
      GF_INSTALL_PLUGINS: "grafana-simple-json-datasource,grafana-piechart-panel,mtanda-histogram-panel,mtanda-heatmap-epoch-panel,neocat-cal-heatmap-panel"
      GF_SERVER_ROUTER_LOGGING: "true"
      GF_SECURITY_DATA_SOURCE_PROXY_WHITELIST: "chameleon:5445"
      GF_AUTH_PROXY_ENABLED: "true"
      GF_PLUGIN_JSON_ANNOTATIONS: "true"
      # GF_SESSION_COOKIE_SECURE: "true" -- redirects too many times?
    volumes: 
      - data-grafana:/var/lib/grafana
    depends_on:
      - chameleon
  chameleon:
    build: .
    ports:
      - "5445:5445"
    environment:
      SERVER_NAME: "localhost:5445"
      GUNICORN_CMD_ARGS: "--bind=0.0.0.0:5445 --access-logfile=-"
      CHAMELEON_PGHOST: "postgres"
      CHAMELEON_PGDB: "chameleon"
      CHAMELEON_PGTAB: "postgres"
      CHAMELEON_PGUSER: "postgres"
      CHAMELEON_PGPASS: "secret"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.2
    ports:
      - "5432"
    volumes:
      - data-postgres:/var/lib/postgresql/data
      - ./postgres/init.d/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "chameleon"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"


volumes:
  data-grafana:
  data-postgres:

